[package]
name = "hello_rust"
version = "0.1.0"
authors = ["Tyler Wright <tyler@devsplained.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
